---
- hosts: hosts
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Install Apache
      yum: name=httpd state=present

    - name: install php
      yum: name=php state=present

    - name: Install PHP module for Apache
      yum: name=php-cli state=present

    - name: Start Apache
      service: name=httpd state=started enabled=yes

    - name: Install "Hello from EC2" PHP single page app
      copy: src=index.php dest=/var/www/html/index.php mode=0664

    - name: Restart Apache
      service: name=httpd state=restarted enabled=yes
